"""
Patchly - Excel Audit Exporter for Human Accessibility Assessment
Generates a structured, professional .xlsx workbook using openpyxl.
"""

import io
from typing import List, Dict, Any
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Color constants for severity tags
SEVERITY_COLORS = {
    "CRITICAL": {"fill": "FEE2E2", "text": "991B1B"}, # Red
    "SERIOUS":  {"fill": "FFEDD5", "text": "9A3412"}, # Orange
    "MODERATE": {"fill": "FEF3C7", "text": "92400E"}, # Amber
    "MINOR":    {"fill": "E0E7FF", "text": "3730A3"}  # Indigo
}

def generate_accessibility_excel(issues: List[Dict[str, Any]], page_title: str = "Webpage Audit") -> io.BytesIO:
    """
    Builds a beautifully formatted Excel workbook in-memory and returns a BytesIO buffer.
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "A11y Human Assessment"
    ws.views.sheetView[0].showGridLines = True

    # 1. Document Title Banner
    ws.merge_cells("A1:J1")
    title_cell = ws["A1"]
    title_cell.value = f"Patchly Accessibility Audit & Human Remediation Tracker - {page_title}"
    title_cell.font = Font(name="Segoe UI", size=14, bold=True, color="FFFFFF")
    title_cell.fill = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
    title_cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 36

    # 2. Subheader Info
    ws.merge_cells("A2:J2")
    info_cell = ws["A2"]
    info_cell.value = f"Total Flags: {len(issues)} | Generated by Patchly Engine | Designed for Compliance Verification"
    info_cell.font = Font(name="Segoe UI", size=10, italic=True, color="64748B")
    info_cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[2].height = 20

    # 3. Table Column Headers
    headers = [
        "Issue #",
        "Severity",
        "Category",
        "WCAG 2.1 Criteria",
        "Element / Tag",
        "Failure Description",
        "Automated Quick Fix / Diff",
        "Human Action Required",
        "Reviewer Status",
        "Reviewer Notes & Initials"
    ]

    header_font = Font(name="Segoe UI", size=11, bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="334155", end_color="334155", fill_type="solid")
    header_align = Alignment(horizontal="center", vertical="center", wrap_text=True)

    thin_border = Border(
        left=Side(style='thin', color='E2E8F0'),
        right=Side(style='thin', color='E2E8F0'),
        top=Side(style='thin', color='E2E8F0'),
        bottom=Side(style='thin', color='E2E8F0')
    )

    ws.row_dimensions[4].height = 28
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=4, column=col_idx, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align
        cell.border = thin_border

    # 4. Populate Issue Data Rows
    body_font = Font(name="Segoe UI", size=10, color="0F172A")
    data_align = Alignment(vertical="top", wrap_text=True)

    for row_idx, issue in enumerate(issues, start=5):
        ws.row_dimensions[row_idx].height = 55
        severity = issue.get("severity", "MODERATE").upper()
        sev_meta = SEVERITY_COLORS.get(severity, {"fill": "F1F5F9", "text": "475569"})

        # Derive human action based on rule type
        rule_id = issue.get("rule_id", "")
        if "video" in rule_id:
            human_action = "Transcribe audio & generate .vtt captions file for upload."
        elif "alt" in rule_id:
            human_action = "Review image context & approve descriptive alt text or mark decorative."
        elif "contrast" in rule_id:
            human_action = "Review brand color palette & approve darker/lighter hex replacement."
        elif "keyboard" in rule_id or "tabindex" in rule_id:
            human_action = "Verify keyboard focus order with Tab key & inspect custom UI widget."
        else:
            human_action = "Conduct manual assistive technology test."

        row_values = [
            f"FLAG-{row_idx-4:03d}",
            severity,
            issue.get("title", ""),
            issue.get("wcag_sc", ""),
            f"<{issue.get('element_tag', 'el')}>",
            issue.get("description", ""),
            issue.get("quick_fix_code", ""),
            human_action,
            "Pending Review",
            "" # Empty for human reviewer notes
        ]

        for col_idx, val in enumerate(row_values, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.font = body_font
            cell.border = thin_border
            cell.alignment = data_align

            # Severity column styling
            if col_idx == 2:
                cell.fill = PatternFill(start_color=sev_meta["fill"], end_color=sev_meta["fill"], fill_type="solid")
                cell.font = Font(name="Segoe UI", size=10, bold=True, color=sev_meta["text"])
                cell.alignment = Alignment(horizontal="center", vertical="top")
            elif col_idx == 1:
                cell.font = Font(name="Segoe UI", size=10, bold=True, color="475569")
                cell.alignment = Alignment(horizontal="center", vertical="top")

    # 5. Auto-fit column widths
    column_widths = {
        1: 12, # Issue #
        2: 14, # Severity
        3: 24, # Category
        4: 28, # WCAG Criteria
        5: 14, # Element
        6: 38, # Description
        7: 42, # Quick Fix
        8: 30, # Human Action
        9: 18, # Status
        10: 25  # Notes
    }

    for col_idx, width in column_widths.items():
        col_letter = get_column_letter(col_idx)
        ws.column_dimensions[col_letter].width = width

    # Save to buffer
    output_stream = io.BytesIO()
    wb.save(output_stream)
    output_stream.seek(0)
    return output_stream
